apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketball-deployment
  labels:
    app: basketball 
    tier: backend
    type: gopher
spec:
  template:
    metadata:
      name: basketball-pod
      labels:
        app: basketball
        tier: backend
        type: gopher
    spec:
      containers:
        - name: basketball-container
          image: basketball:latest
          imagePullPolicy: Never
          env:
            - name: ENVIRONMENT
              value: "DEV"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: RUNTIME_PORT
              value: "8090"
            - name: STORAGE_FILENAME
              value: "1583510437-test.yaml"
  replicas: 2
  selector:
    matchLabels:
      app: basketball
      tier: backend
